package com.ireceptorplus.ireceptorchainclient.MetadataServiceAPI.Controllers;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.ireceptorplus.ireceptorchainclient.FileStorage.DatasetStorageService;
import com.ireceptorplus.ireceptorchainclient.FileStorage.StorageService;
import com.ireceptorplus.ireceptorchainclient.MetadataServiceAPI.DTOs.DatasetDTO;
import com.ireceptorplus.ireceptorchainclient.MetadataServiceAPI.Models.Dataset;
import com.ireceptorplus.ireceptorchainclient.MetadataServiceAPI.Services.DatasetService;
import com.sun.istack.NotNull;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.Date;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@RestController
@RequestMapping("api/dataset")
@CrossOrigin(origins = "${app.resourceAllowedOrigins}")
public class DatasetController
{
    @Autowired
    private DatasetService datasetService;

    @Autowired
    private ModelMapper modelMapper;

    @Autowired
    private DatasetStorageService storageService;

    @Autowired
    private ObjectMapper objectMapper;

    /**
     * Returns all Dataset objects stored.
     * @return An array containing all the DataProcessing objects stored.
     */
    @GetMapping
    public List<Dataset> getDatasets()
    {
        return datasetService.readAll();
    }

    /**
     * Returns a specific Dataset, with the id received as parameter.
     * @param id The id of the Dataset to be retrieved
     * @return The Dataset with the id
     */
    @GetMapping("/{id}")
    public Optional<Dataset> getDataset(@PathVariable @NotNull Long id) {
        return datasetService.readById(id);
    }

    /**
     * Creates a new Dataset and respective file. Both the metadata of the Dataset and the file are received as parameters on this same request.
     * @param datasetStr A string with the JSON representation of the Dataset object
     * @param file A multipart file that is associated with the Dataset
     * @return The new instance of the Dataset that was just created, contains the id automatically generated by the DB.
     */
    @PostMapping(consumes = {MediaType.MULTIPART_FORM_DATA_VALUE, MediaType.APPLICATION_JSON_VALUE})
    public DatasetDTO createDataset(@RequestParam("metadata") String datasetStr,
                                    @RequestParam("file") MultipartFile file)
    {
        DatasetDTO datasetDTO = null;
        try
        {
            datasetDTO = objectMapper.readValue(datasetStr, DatasetDTO.class);
        } catch (JsonProcessingException e)
        {
            e.printStackTrace();
            return null;
        }
        String originalFileName = file.getOriginalFilename();
        UUID uuid = UUID.randomUUID();
        datasetDTO.setUuid(uuid);
        storageService.store(file, uuid.toString());

        Dataset dataset = modelMapper.map(datasetDTO, Dataset.class);
        dataset.setCreationDate(new Date());
        dataset.setOriginalFileName(originalFileName);

        Dataset createdDataset = datasetService.create(dataset);
        DatasetDTO createdDatasetDTO = modelMapper.map(createdDataset, DatasetDTO.class);

        return createdDatasetDTO;
    }
}
