package com.ireceptorplus.ireceptorchainclient.MetadataServiceAPI.Controllers;

import com.ireceptorplus.ireceptorchainclient.MetadataServiceAPI.DTOs.ToolDTO;
import com.ireceptorplus.ireceptorchainclient.MetadataServiceAPI.Models.Tool;
import com.ireceptorplus.ireceptorchainclient.MetadataServiceAPI.Services.ToolService;
import com.sun.istack.NotNull;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("api/tool")
@CrossOrigin(origins = "${app.resourceAllowedOrigins}")
public class ToolController
{
    @Autowired
    private final ToolService toolService;

    @Autowired
    private ModelMapper modelMapper;

    public ToolController(ToolService toolService)
    {
        this.toolService = toolService;
    }

    /**
     * Returns all Tool objects stored.
     * @return An array containing all the Tool objects stored.
     */
    @GetMapping
    public List<Tool> getTools()
    {
        return toolService.readAll();
    }

    /**
     * Returns a specific Tool, with the id received as parameter.
     * @param id The id of the Tool to be retrieved
     * @return The Tool with the id
     */
    @GetMapping("/{id}")
    public Optional<Tool> getTool(@PathVariable @NotNull Long id) {
        return toolService.readById(id);
    }

    /**
     * Creates a new Tool object.
     * @param toolDTO The new instance of Tool to be created
     * @return The new instance of the Tool that was just created, contains the id automatically generated by the DB.
     */
    @PostMapping
    public ToolDTO createTool(@RequestBody @Valid ToolDTO toolDTO)
    {
        Tool tool = modelMapper.map(toolDTO, Tool.class);
        Tool createdTool = toolService.create(tool);
        ToolDTO createdToolDTO = modelMapper.map(createdTool, ToolDTO.class);

        return createdToolDTO;
    }

}
