version: '3'

services:


  db:
    image: postgres:12
    volumes:
      - middleware_db:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      # default user is 'postgres'
      POSTGRES_DB: ireceptorchain-storage-service
      POSTGRES_PASSWORD: password

  storage-service:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  middleware_db:
