version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - ireceptorchain-storage-service-db:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      # default user is 'postgres'
      POSTGRES_DB: ireceptorchain-storage-service
      POSTGRES_PASSWORD: password
    restart: always

volumes:
  ireceptorchain-storage-service-db:
