version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - ireceptorchain-storage-service-db:/var/lib/postgresql/data:delegated
    expose:
      - 5432
    environment:
      # default user is 'postgres'
      POSTGRES_DB: ireceptorchain-storage-service
      POSTGRES_PASSWORD: password
    restart: always

  storage-service:
    build: ../
    volumes:
      - ../src:/storage/src
      - ./config:/storage/config
      - ./files:/storage/files
    environment:
      - PROPERTIES_PATH=/storage/config/trialreceptor.properties
    depends_on:
      - db
    restart: always
    networks:
      - default
      - apache_ireceptor-network

networks:
  default:

  apache_ireceptor-network:
    external: true

volumes:
  ireceptorchain-storage-service-db:
