version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - ireceptorchain-storage-service-db:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      # default user is 'postgres'
      POSTGRES_DB: ireceptorchain-storage-service
      POSTGRES_PASSWORD: password
    restart: always

  storage-service:
    build: ../
    volumes:
      - ../src:/storage/src
      - ./config:/storage/config
      - ./files:/storage/files
      - /var/run/docker.sock:/var/run/docker.sock
      - ./processingFiles:/storage/processingFiles
      - ../tools-containers:/storage/tools-containers
      - ../wallets:/storage/wallets
      - ../../ireceptorchain/test-network/organizations:/ireceptorchain/test-network/organizations
    environment:
      - PROPERTIES_PATH=/storage/config/trialreceptor.properties
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080

networks:
  default:

  apache_ireceptor-network:
    external: true

volumes:
  ireceptorchain-storage-service-db:
