version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - ireceptorchain-storage-service-db:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      # default user is 'postgres'
      POSTGRES_DB: ireceptorchain-storage-service
      POSTGRES_PASSWORD: password
    restart: always
    networks:
      - storage-service-network

  blockchain-certificate-creation:
    build:
      context: ../blockchain-certificate-creation
    volumes:
      - ../wallets:/wallets
      - ../../ireceptorchain/test-network/organizations:/ireceptorchain/test-network/organizations
      - ../../ireceptorchain/production-network/blockchain/mainNetwork/organizations:/ireceptorchain/production-network/blockchain/mainNetwork/organizations
    networks:
      - hyperledger_test_network
      - hyperledger_production_network
      - apache_ireceptor-network
      - default
      - storage-service-network
    env_file:
      - ../env/ca.env
      - ../env/general.env
    environment:
      - WALLET_USER_ID=${WALLET_USER_ID}
      - ORG_DOMAIN=${ORG_DOMAIN}
      - ORG_CA_DOMAIN=${ORG_CA_DOMAIN}
      - NETWORK_CONFIG_PATH=${NETWORK_CONFIG_PATH}

  storage-service:
    build: ../
    volumes:
      - ../src:/storage/src
      - ./config:/storage/config
      - ./files:/storage/files
      - /var/run/docker.sock:/var/run/docker.sock
      - ./processingFiles:/storage/processingFiles
      - ../tools-containers:/storage/tools-containers
      - ../wallets:/wallets
      - ../../ireceptorchain/test-network/organizations:/ireceptorchain/test-network/organizations
      - ../../ireceptorchain/production-network/blockchain/mainNetwork/organizations:/ireceptorchain/production-network/blockchain/mainNetwork/organizations
    environment:
      - PROPERTIES_PATH=/storage/config/trialreceptor.properties
      - ORG_DOMAIN=${ORG_DOMAIN}
      - ORG_CONNECTION_FILE=${ORG_CONNECTION_FILE}
      - WALLET_USER_ID=${WALLET_USER_ID}
      - ORG_CA_MSP_ID=${ORG_CA_MSP_ID}
      - ORG_CA_AFFILIATION=${ORG_CA_AFFILIATION}
      - NETWORK_CONFIG_PATH=${NETWORK_CONFIG_PATH}
      - CA_CERT_PATH=${CA_CERT_PATH}
    depends_on:
      - db
      - blockchain-certificate-creation
    restart: always
    ports:
      - 8080:8080
    networks:
      - hyperledger_test_network
      - hyperledger_production_network
      - apache_ireceptor-network
      - default
      - storage-service-network
    env_file:
      - ../env/general.env


networks:
  default:

  hyperledger_test_network:
    name: fabric_test
  
  hyperledger_production_network:
    name: ireceptorchain
    external: true
    driver: overlay

  apache_ireceptor-network:
    external: true

  storage-service-network:
    external: true

volumes:
  ireceptorchain-storage-service-db:
