create table processing_step
(
    id                 int8 generated by default as identity,
    blockchain_state   int4,
    creation_date      timestamp,
    description        varchar(255),
    name               varchar(255),
    step_order         int8,
    command_id         int8,
    data_processing_id int8,
    primary key (id)
)