create table command (
                         id int8 generated by default as identity,
                         command_string varchar(255),
                         tool_id int8,
                         primary key (id)
)