create table script
(
    id                  int8 generated by default as identity,
    script_type         int4,
    url                 varchar(255),
    uuid                varchar(255),
    created_pipeline_id int8,
    primary key (id)
)