create table tool
(
    id             int8 generated by default as identity,
    description    varchar(255),
    docs_reference varchar(255),
    name           varchar(255),
    url            varchar(255),
    version        varchar(255),
    primary key (id)
)