create table created_pipeline
(
    id            int8 generated by default as identity,
    creation_date timestamp,
    description   varchar(255),
    name          varchar(255),
    state         int4,
    command_id    int8,
    primary key (id)
);

create table created_pipeline_input_datasets
(
    created_pipeline_id int8 not null,
    input_datasets_id   int8 not null
);